# @package agent
_target_: agent.ourc.OURCAgent
name: ourc
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 32
#feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
update_skill_every_step: 50
nstep: 3
batch_size: 32
init_critic: true
update_encoder: ${update_encoder}

replay_buffer_size: ${replay_buffer_size}
contrastive_update_rate: 3
temperature: 0.07
contrastive_scale: 1.0

obs_dim: 1
skill_dim: 16
ncol: 13
nrow: 13
epsilon: 0.1
alpha: 0.1
gamma: 0.1